name: 'Simplecov Coverage Converter'
description: 'Converts Simplecov code coverage result files into a plain JSON format'
author: 'Michael Adams'

inputs:
  coverage-file:
    description: 'Shell glob to the JSON file(s) containing coverage data'
    required: false
    default: 'coverage/.resultset.json'
  remove-prefix:
    description: 'Common prefix to remove from filenames to convert from absolute paths to relative paths'
    required: false
    default: 'github_workspace'

outputs:
  coverage-file:
    description: 'Coverage data converted to plain JSON format'

runs:
  using: 'node20'
  main: 'dist/index.js'
