name: Sanity test of action

on:
  push:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./
        with:
          coverage-file: "src/__tests__/.resultset.json"
          remove-prefix: "/user/code"

      # exits with 0 if no differences were found
      - name: Compare with expected output
        run: diff <(jq --sort-keys . coverage.json) <(jq --sort-keys . src/__tests__/expected.json)
